export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "";
export const VITE_BASE_PATH = import.meta.env.VITE_BASE_PATH || "";

export const ROUTE_URL = {
  login: "/rbi_deployment/admin/login",
  dashboard: "/rbi_deployment/admin",
  adminDashboard: "/rbi_deployment/admin/adminDashboard",
  createUser: "/rbi_deployment/admin/createUser",
  viewUser: "/rbi_deployment/admin/viewUser",
  createCitizens: "/rbi_deployment/admin/createCitizens",
  createWorkShop: "/rbi_deployment/admin/createWorkShop",
  mapCitizen: "/rbi_deployment/admin/uploadCitizen",
  vleDashboard: "/rbi_deployment/admin/VLEDashboard",
  uploadTestimony: "/rbi_deployment/admin/uploadTestimony",
  uploadVle: "/rbi_deployment/admin/uploadVle",
  ViewWorkshop: "/rbi_deployment/admin/ViewWorkshop",
  viewTestimony: "/rbi_deployment/admin/viewTestimony",
  viewCitizenByCard: "/rbi_deployment/admin/viewCitizenDetails",
  viewSession: "/rbi_deployment/admin/viewSession",
  testimonyByWorkshop : "/rbi_deployment/admin/testimonyByWorkshop",
};

export const API_URL = {
  login: "user-login",
  createUser: "create-user",
  createWorkShop: "/createWorkShop",
  createCitizen: "/createCitizens",
  getWorkshop: "/getWorkshop",
  uploadCitizens: "/uploadCitizens",
  uploadTestimony: "/update-testimony",
  uploadVle: "/upload-vle",
  getWorkshopByFilters: "/getWorkshopByFilters",
  updateChecklist: "/updateChecklist",
  updateStatus: "/updateStatus",
  viewTestimony: "/get-testimony-by-user-workshop",
  vleDasboard: "/get-vle-dashboard-card",
  getCitizens: "/getCitizens",
  getWorkshopDetails: "/getWorkshopDetails",
  getallusers: "get-all-users",
  updateUsers: "/update-users-details",
  deleteUser: "/delete-user",
  updatePassword: "/update-users-password",
  getLocationManager: "/getLocationManager",
  genderWiseDonut: "/genderWiseDonut",
  locationWiseBarChart: "/locationWiseBarChart",
  getDistrict: "/getDistrict",
  getWorkShop: "/get-workshop-list",
  getVLE: "/get-users-lookup",
  getWorkshopStatus: "/get-workshop-status-values",
};
